#!/usr/bin/env bash
# This Script connects to the server 54.210.52.104 using the users private key
# stored in a file school Found in the users home directory

ssh -i ~/.ssh/school ubuntu@54.210.52.104
